### PR TITLE
Do not overwrite custom CollectionInputFilter.

### PR DESCRIPTION
**Pull request by darckking**
Signed-off-by: illia <illia.gapak@ffflabel.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

This is a solution for issue #18  I posted last year. As there was no response so far I decided to create a pull request.

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
This kind of change requires test additions for validation and regression prevention

**Review by Ocramius — APPROVED** [review]
LGTM. Need someone else's review too, to see if this is the valid approach, but it is OK from my PoV.

**Comment by Ocramius** [comment]
Also to be clarified: do we want this in `1.10.x`, or `1.11.x` (next minor)?

**Review by weierophinney — APPROVED** [review]
This makes total sense to me.

Yes, it's a bugfix, but also a _behavior change_, so I'd argue we leave it for new minor.

**Pull request merged**
